---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJwMWdmeTA1Cg==
  CLOUDINARY_KEY: NzIyODc2OTk4MTQ2MTUxCg==
  CLOUDINARY_SECRET: VExEd2xXTEJ2bGJaZlptMjU5dHgtcy1mSl9jCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2lZV1J0YVc0NU1URWlMQ0poSWpvaVkyMDBjamh4YURsNk1ESmhkVEpwY1hkbGJETTJaV0p2WXlKOS5XdlFRdHFkLUVDM0NKM0Y5bmcwQ2dnCg==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZGl0eWFqYWlzd2FsODc1NDQ6QWRtaW4xMjNAYm9vdGNhbXAudzJkd3YubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUJvb3RjYW1wCg==
  SECRET: ZGV2b3Bzc2hhY2sK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: aditya0211/camp:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health  # If your app has a /health endpoint, use that
              port: 3000
            initialDelaySeconds: 60   # Give more time for app startup
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health  # Ensure this is the correct path for health check
              port: 3000
            initialDelaySeconds: 60   # Increased delay for readiness probe
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
